// Irregular inflections → base form. Suffix rules can't derive these
// (ran → run), so they're listed explicitly. Only forms that are safe to
// merge for a learner: past tenses, participles and irregular plurals.
export const IRREGULAR: Record<string, string> = {
  // --- verbs: past / participle → base ---
  ate: 'eat', eaten: 'eat',
  became: 'become',
  began: 'begin', begun: 'begin',
  bent: 'bend',
  bit: 'bite', bitten: 'bite',
  blew: 'blow', blown: 'blow',
  broke: 'break', broken: 'break',
  brought: 'bring',
  built: 'build',
  bought: 'buy',
  caught: 'catch',
  chose: 'choose', chosen: 'choose',
  came: 'come',
  crept: 'creep',
  dealt: 'deal',
  dug: 'dig',
  drew: 'draw', drawn: 'draw',
  drank: 'drink', drunk: 'drink',
  drove: 'drive', driven: 'drive',
  fell: 'fall', fallen: 'fall',
  fed: 'feed',
  felt: 'feel',
  fought: 'fight',
  flew: 'fly', flown: 'fly',
  forgot: 'forget', forgotten: 'forget',
  forgave: 'forgive', forgiven: 'forgive',
  froze: 'freeze', frozen: 'freeze',
  gave: 'give', given: 'give',
  got: 'get', gotten: 'get',
  went: 'go', gone: 'go',
  grew: 'grow', grown: 'grow',
  heard: 'hear',
  hid: 'hide', hidden: 'hide',
  held: 'hold',
  found: 'find',
  kept: 'keep',
  knew: 'know', known: 'know',
  laid: 'lay',
  led: 'lead',
  learnt: 'learn',
  lent: 'lend',
  made: 'make',
  saw: 'see', seen: 'see',
  stuck: 'stick',
  lit: 'light',
  lost: 'lose',
  meant: 'mean',
  met: 'meet',
  paid: 'pay',
  rode: 'ride', ridden: 'ride',
  rang: 'ring', rung: 'ring',
  rose: 'rise', risen: 'rise',
  ran: 'run',
  sang: 'sing', sung: 'sing',
  sank: 'sink', sunk: 'sink',
  sat: 'sit',
  said: 'say',
  sold: 'sell',
  sent: 'send',
  shook: 'shake', shaken: 'shake',
  shot: 'shoot',
  showed: 'show', shown: 'show',
  slept: 'sleep',
  spoke: 'speak', spoken: 'speak',
  spent: 'spend',
  spun: 'spin',
  stood: 'stand',
  stole: 'steal', stolen: 'steal',
  struck: 'strike',
  swam: 'swim', swum: 'swim',
  swore: 'swear', sworn: 'swear',
  taught: 'teach',
  tore: 'tear', torn: 'tear',
  told: 'tell',
  threw: 'throw', thrown: 'throw',
  took: 'take', taken: 'take',
  understood: 'understand',
  woke: 'wake', woken: 'wake',
  wore: 'wear', worn: 'wear',
  won: 'win',
  wrote: 'write', written: 'write',
  sought: 'seek',
  bound: 'bind',
  fled: 'flee',
  bred: 'breed',
  swept: 'sweep',
  wept: 'weep',
  hung: 'hang',
  slid: 'slide',
  strove: 'strive',
  sprang: 'spring', sprung: 'spring',

  // --- irregular plurals → singular ---
  children: 'child',
  men: 'man',
  women: 'woman',
  feet: 'foot',
  teeth: 'tooth',
  mice: 'mouse',
  geese: 'goose',
  lives: 'life',
  knives: 'knife',
  wives: 'wife',
  leaves: 'leaf',
  loaves: 'loaf',
  halves: 'half',
  shelves: 'shelf',
  wolves: 'wolf',
  thieves: 'thief',
  phenomena: 'phenomenon',
  criteria: 'criterion',
};

// Words that look inflected but are their own lexemes — never suffix-strip.
export const NO_LEMMA = new Set<string>([
  'evening', 'morning', 'nothing', 'something', 'everything', 'anything',
  'during', 'thing', 'being', 'king', 'ring', 'sing', 'wing', 'spring',
  'string', 'bring', 'universe', 'news', 'species', 'series',
  'physics', 'politics', 'economics', 'mathematics', 'analysis', 'basis',
  'crisis', 'lens', 'bus', 'gas', 'chaos', 'canvas', 'atlas', 'bias',
  'census', 'circus', 'campus', 'status', 'virus', 'bonus', 'famous',
]);
